### ISSUE TITLE
XUnmapWindow

### ISSUE THREAD

**Issue by matzrm** [lukas-w/qt5-x11embed#1]
When I try to use the lib, I obtain this error:

-1: error: /libqx11embedcontainer.a(X11EmbedContainer.cpp.o): undefined reference to symbol 'XUnmapWindow'

/usr/lib/x86_64-linux-gnu/libX11.so.6:-1: error: error adding symbols: DSO missing from command line

**Comment by lukas-w** [comment]
@matzrm Why did you close this? Have you resolved the issue? If yes, what did you do to fix it?

**Comment by matzrm** [comment]
Hi Lukas,
adding -lX11 to .pro resolve this issue. Also -lxcb is needed to right compile a simple project using your lib.

**Comment by lukas-w** [comment]
@matzrm I see, you were providing your own `.pro` file. This project is using CMake instead of qmake, but we can include a working `.pro` file if desired.
