### ISSUE TITLE
Something's wrong with CMake

### ISSUE THREAD

**Issue by zapashcanon** [lukas-w/qt5-x11embed#2]
Hi,

I got this error while trying to build LMMS on Debian Unstable:

```sh
/home/zapashcanon/Programmation/C++/lmms/src/3rdparty/qt5-x11embed/src/X11EmbedContainer.cpp:40:10: fatal error: 'QtCore/private/qobject_p.h' file not found
#include <QtCore/private/qobject_p.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/3rdparty/qt5-x11embed/CMakeFiles/qx11embedcontainer.dir/build.make:63: src/3rdparty/qt5-x11embed/CMakeFiles/qx11embedcontainer.dir/src/X11EmbedContainer.cpp.o] Error 1
```

Looks like this come from this repo. I'm not particularly an expert in CMake, maybe you'll be able to tell me what's wrong here.

**Comment by lukas-w** [comment]
@zapashcanon You're missing the package `qtbase5-private-dev`. The fact that CMake doesn't report the package missing is a bug within LMMS.

If this doesn't fix it and you can't build the code from this repo either (without LMMS), please reopen.

**Comment by zapashcanon** [comment]
Ok, will try it. If it fixes the issue, I'll open an issue against the LMMS repo.
